-- MedDocs Stage 1: initial schema.
-- pgvector extension provides the `vector` type and distance operators (<=>, <->, <#>).
CREATE EXTENSION IF NOT EXISTS vector;

-- ---------------------------------------------------------------------------
-- users: one row per registered account. Password is a BCrypt hash (Stage 2).
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- documents: an uploaded source file owned by a user. status drives the
-- async ingestion lifecycle (PENDING -> INDEXED | FAILED, Stage 3).
-- ---------------------------------------------------------------------------
CREATE TABLE documents (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    source_label   VARCHAR(255) NOT NULL,
    filename       VARCHAR(255),
    status         VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    failure_reason TEXT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_documents_user_id ON documents (user_id);

-- ---------------------------------------------------------------------------
-- chunks: overlapping text windows of a document, each with its embedding.
-- vector(384) is fixed to the all-MiniLM-L6-v2 embedder (see ROADMAP §Stage 1).
-- ---------------------------------------------------------------------------
CREATE TABLE chunks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT       NOT NULL REFERENCES documents (id) ON DELETE CASCADE,
    chunk_index INTEGER      NOT NULL,
    content     TEXT         NOT NULL,
    section_ref VARCHAR(255),
    embedding   vector(384),
    UNIQUE (document_id, chunk_index)
);

CREATE INDEX idx_chunks_document_id ON chunks (document_id);
